Add PostgreSQL cache
HazyResearch/manifest pull request #53
Opened 2023-01-30 16:54 UTC by seyuboglu

This cache works with GCP CloudSQL, making it easier to setup caches that are shared among users. 

Question: it introduces some optional dependencies 
```
   "pg8000",
        "google-cloud-storage",
        "sqlalchemy",
```
What's manifest's way of ensuring that these don't break imports for folks who don't have them installed?

2023-01-30 20:48 UTC, lorr1 commented
At the moment, a try/catch around the cache dictionary in `manifest.py`. So the postgres key only gets added if the class is loaded sucessfully.

2023-01-30 20:54 UTC, lorr1 commented
Also how hard would adding a test be. See https://github.com/HazyResearch/manifest/blob/c306e16da6d320f397db0705a278cd94158eeb44/tests/conftest.py#L20. I have support for instantiating different caches. If it's too hard or costs money, it's not worth it except maybe some get/set key methods. I certainly don't test all the clients lol.

2023-01-30 20:54 UTC, lorr1 requested changes
Fix tests formatting please!

2023-01-30 20:54 UTC, lorr1 commented on manifest/manifest.py
> +    "postgres": PostgreSQLCache
So try cache around here for import issues.

2023-01-30 20:54 UTC, lorr1 commented on manifest/caches/postgres.py
> +                user=cache_args.pop("user"),
We probably want to set these as `pg_user` or `cache_user` or something so it's clear this is a cache param. Ideally we should refactor to get a clearer set of input params for a cache like we have for request, but this is fine for now. It'll happen once there are 2-3 caches that need params.

2023-01-30 20:54 UTC, lorr1 commented on manifest/caches/postgres.py
> +            print("Creating database...")
Logger.info?

2023-02-08 06:27 UTC, seyuboglu commented
Just added in some simple tests that monkeypatch the connection to the db

2023-02-09 21:52 UTC, lorr1 approved these changes
A few nits and make sure tests pass.

2023-02-09 21:52 UTC, lorr1 commented on manifest/caches/postgres.py
> +"""SQLite cache."""
nit: Change comment to be postgres.

2023-02-09 21:52 UTC, lorr1 commented on tests/conftest.py
> +def postgres_cache(monkeypatch):
You probably need to add a type here. But this is pretty smart

2023-02-14 17:46 UTC, merged